version: '3.8'
services:

  mongo:
    image: mongo:4.4.3
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: blog_db

    volumes:
      - ./infastructure/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

