version: '3.8'
services:
  blog-service:
    build:
      context: .
      dockerfile: Dockerfile-blog-service

    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.3
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: blog_db

    volumes:
      - ./infastructure/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

